### ISSUE TITLE
version1 fields should not be required/mandatory

### ISSUE THREAD

**Issue by zargot** [Big-Life-Lab/PHES-ODM-Validation#103]
when generating a version1 schema from v2 parts, the 'required' schema attribute should not be set. This is because version1 did not have mandatory fields.

**Comment by DougManuel** [comment]
After discussing, let's go back to the original plan to have fields the equivalent mandatory fields in version 2 be mandatory in version 1.

**Comment by yulric** [comment]
Ok, in that case I'll close this issue.
