### ISSUE TITLE
Refactor the way `gen_cerb_rules` and `gen_schema` works for each Rule object

### ISSUE THREAD

**Issue by yulric** [Big-Life-Lab/PHES-ODM-Validation#121]
`gen_schema` goes through pretty much the same logic for all the rule objects which is iterating through each table, iterating through attribute, and setting the schema for that attribute for each rule. The only unique behavior is in the `gen_cerb_rule` function for each rule. We should probably make `gen_schema` generic for all rules with the custom behavior of adding the rule specific schema pieces within the `gen_cerb_rule` function.

**Comment by zargot** [comment]
`gen_schema` is being implemented with different logic across the rule depending on which attributes should have the rule, etc. Can you take another look and see if you still think we should do this, @yulric?

**Comment by yulric** [comment]
> `gen_schema` is being implemented with different logic across the rule depending on which attributes should have the rule, etc. Can you take another look and see if you still think we should do this, @yulric?

We can close this issue for now because I think it will be irrelevant once custom rules needs to be implemented.
