### ISSUE TITLE
Add the ability to turn off a rule in the `validate_data` function

### ISSUE THREAD

**Issue by yulric** [Big-Life-Lab/PHES-ODM-Validation#150]

**Comment by zargot** [comment]
we already have a whitelist for this. should i make it easy to add all rules except one to the whitelist, or add an additional "blacklist"? I think whitelist-only is cleanest.

**Comment by yulric** [comment]
1. Hmm, I think blacklist would be better for the user? At least currently, it seems like MECP wants only a blacklist.
2. Agreed with list of rules being added to the report.
