### ISSUE TITLE
Duplicate entries are being thrown for the siteID field in the SiteMeasure table. This is in the TMU lab data.

### ISSUE THREAD

**Issue by yulric** [Big-Life-Lab/PHES-ODM-Validation#152]

**Comment by zargot** [comment]
the data rows are not unique.

**Comment by yulric** [comment]
But isn't siteID not a primary key in the SiteMeasure table? At least, that's what I'm seeing in the latest dictionary version.

**Comment by zargot** [comment]
It may be related to the issues I'm having with the SiteMeasure table in #153
