### ISSUE TITLE
Invalid category errors are being thrown for `wwFlow` values in the categorical type field in the SiteMeasure table

### ISSUE THREAD

**Issue by yulric** [Big-Life-Lab/PHES-ODM-Validation#153]

**Comment by zargot** [comment]
Table SiteMeasure is not in the schema. The input data table name is also being wrongly inferred as table Site, and wwFlow is not part of Site.type.

**Comment by yulric** [comment]
1. I think SiteMeasure should be in the schema but this is most probably an issue in the dictionary
2. Is it being wrongly inferred because of your code or...?

**Comment by zargot** [comment]
I think it happens because SiteMeasure isn't part of the tables I've been able to extract from the parts
