### ISSUE TITLE
Missing mandatory column error is being thrown for the siteID column in the WWMeasure table

### ISSUE THREAD

**Issue by yulric** [Big-Life-Lab/PHES-ODM-Validation#154]

**Comment by zargot** [comment]
column siteID is missing in input data, and from my understanding of the dictionary it is required in table WWMeasure.

**Comment by yulric** [comment]
From what I'm seeing in the latest (online) version of the dictionary, siteID is only in the Site table? So, I'm not sure why its throwing this error in the WWMeasure.

**Comment by zargot** [comment]
i found it as a fK in the measures table (WWMeasure -> measures, SiteID -> siteID)

**Comment by zargot** [comment]
and measuresRequired=mandatory

**Comment by zargot** [comment]
Closing, as it seems to work correctly now.
