### ISSUE TITLE
`index` column in the WWMeasure table should be a varchar

### ISSUE THREAD

**Issue by yulric** [Big-Life-Lab/PHES-ODM-Validation#155]

**Comment by zargot** [comment]
I guess this is an ODM-dictionary issue. I can add updated parts and regenerate schemas when the new worksheet is released.

**Comment by yulric** [comment]
Dictionary should be updated to a varchar

**Comment by zargot** [comment]
@yulric, I'm moving this to 'next minor release', as it requires a new version of the dictionary with breaking changes.

**Comment by zargot** [comment]
fixed in #171
