### ISSUE TITLE
Invalid type errors are being thrown for datetime values that look like 2023-02-09 12:20. This is for the dateTime, dateTimeStart, and dateTimeEnd columns in the WWMeasure table.

### ISSUE THREAD

**Issue by yulric** [Big-Life-Lab/PHES-ODM-Validation#156]

**Comment by zargot** [comment]
I'm not able to find this in my (new) errors. Maybe it's fixed already.

**Comment by yulric** [comment]
Ok, I can double check. Is it passing on the version that's on main?

**Comment by zargot** [comment]
yes, i was testing on the summary branch but it should be the same

**Comment by zargot** [comment]
Closing, as I don't get this error on main.
