### ISSUE TITLE
Don't show invalid type errors for cells that have null values and are not mandatory

### ISSUE THREAD

**Issue by yulric** [Big-Life-Lab/PHES-ODM-Validation#157]
This is hapenning for the `geoLat` column in the Site table

**Comment by zargot** [comment]
there are no errors in Site table with current version :)

**Comment by yulric** [comment]
Is this for the library version that's on main?

**Comment by zargot** [comment]
yes, tested with the summary branch but should be the same

**Comment by zargot** [comment]
Closing, as it's resolved in main.
