### ISSUE TITLE
[Bug]: failed to get latest ODM version

### ISSUE THREAD

**Issue by ctdegroot** [Big-Life-Lab/PHES-ODM-Validation#206]
### Bug Description

I installed according to the instructions using pip. If I launch Python and try:
```from odm_validation.validation import validate_data``` 
I get the error "failed to get latest ODM version”

### The operating system on which the bug occured

MacOS 13.6.1

### Python Version

3.10.13

**Comment by yulric** [comment]
@zargot I believe the error is because the assets directory is not being included when the package is installed, hence the error.

**Comment by ctdegroot** [comment]
@zargot I just gave this a try but I got the same error and don't see the package assets. I think it might be because the PR is not merged yet. Let me know.

**Comment by zargot** [comment]
@ctdegroot, did you try uninstall followed by install with `@206-pkg-assets`? I'll merge it today, but after that you'll have to specify `@dev` instead of `@main` when you install, like i mentioned above. Let me know how it goes.

**Comment by zargot** [comment]
@ctdegroot, that's great news! The PR is now merged, so you can switch to the dev branch if you'd like.
