### ISSUE TITLE
[Bug]: duplicate_entries_found triggered on setID

### ISSUE THREAD

**Issue by zargot** [Big-Life-Lab/PHES-ODM-Validation#223]
### Bug Description

unclear if this is an error in the ODM definition, or if the code is supposed to handle this primary-key exception, or if this is user error.

error msg: `sets(setID, 4,5):  [duplicate_entries_found]`

![image](https://github.com/user-attachments/assets/e31af664-d41f-444f-8cbe-82ad7e4f9f43)

### The operating system on which the bug occured

linux

### Python Version

3.8

**Comment by zargot** [comment]
@yulric, do you know who's at fault here?

**Comment by zargot** [comment]
> Was this error generated when creating new schema files? Or when validating a data file?

all the bug reports I made recently are just from validating the delatolla dataset.

**Comment by zargot** [comment]
oh, it's not supposed to validate the parts and sets tables, is it?

**Comment by yulric** [comment]
Nope

**Comment by zargot** [comment]
right, then I will automatically exclude those.

**Comment by yulric** [comment]
Why was the tool validating the dictionary? Were they in the data you were testing?

**Comment by zargot** [comment]
> Why was the tool validating the dictionary? Were they in the data you were testing?

yeah, the delatolla excel file including the dictionary, apparently.
