### ISSUE TITLE
[Bug]: "TRUE" is not accepted as a boolean value

### ISSUE THREAD

**Issue by zargot** [Big-Life-Lab/PHES-ODM-Validation#224]
### Bug Description

parts:
![image](https://github.com/user-attachments/assets/2654eb0b-90af-40b7-9722-941734437ebd)

measures:
![image](https://github.com/user-attachments/assets/d702f428-8a4c-4966-8b97-32fe05632b80)

error:
`measures(reportable, 2): Column reportable is a boolean but has value "TRUE". Allowed values are false/true. [invalid_type]`

### The operating system on which the bug occured

linux

### Python Version

3.8

**Comment by zargot** [comment]
@yulric, should we make this case-insensitive?

**Comment by yulric** [comment]
According to the docs, [it should be case-sensitive](https://github.com/Big-Life-Lab/PHES-ODM-Validation/blob/main/docs/validation-rules/invalid_type.qmd#L102-L104) but we can confirm with the team if you want.

**Comment by zargot** [comment]
I will keep case-sensitivity as agreed upon in the meeting, and fix the code so that it expects the right case.
