### ISSUE TITLE
[Bug]: missing phone number triggers min-length rule

### ISSUE THREAD

**Issue by zargot** [Big-Life-Lab/PHES-ODM-Validation#226]
### Bug Description

@yulric, shouldn't this only trigger the missing-required-value rule when it's empty, if it's required in the first place?

error:
`contacts(phone, 2): Value "" (of length 0) is less than the min length of "10" [less_than_min_length]`

### The operating system on which the bug occured

linux

### Python Version

3.8

**Comment by yulric** [comment]
Yes, since an empty string is considered null/missing, this should not trigger a length rule. It could trigger a missing values found rule if its enabled for that column.
