### ISSUE TITLE
implement duplicate_entries_found rule

### ISSUE THREAD

**Issue by yulric** [Big-Life-Lab/PHES-ODM-Validation#30]
Spec: https://validate-docs.phes-odm.org/validation-rules/duplicate_entries_found.html

**Comment by yulric** [comment]
Blocked by #63

**Comment by zargot** [comment]
@yulric, what about calling the cerberus rule 'unique' instead of 'noDuplicateEntries'?

**Comment by yulric** [comment]
When we made a document on adding a new rule, we decided that the rule ID should encode the **failure** rather than the success. You can see it here https://github.com/Big-Life-Lab/PHES-ODM-Validation/blob/main/docs/validation-rules/README.md?plain=1#L29.

So `unique` means that the rule is a success (all entries are unique) which makes it not consistent with the way the other rule IDs are named.

**Comment by zargot** [comment]
I understand that our rule ids are like that, and that's fine, but this is only about the name of the custom cerberus rule that we're adding to the schema. All other cerberus rule names define how the value should be: allowed, required, min, max, etc. So I still think 'unique' is a good idea. It won't affect our rule id.

**Comment by yulric** [comment]
Oh, I see, yes that totally works.
