### ISSUE TITLE
Add new schema_additions argument to the generate_schema function

### ISSUE THREAD

**Issue by yulric** [Big-Life-Lab/PHES-ODM-Validation#36]
The specifications PR https://github.com/Big-Life-Lab/PHES-ODM-Validation/pull/33/files

**Comment by zargot** [comment]
what if the user wants to use an existing schema from the repo, just with additions? Maybe we should have it as a separate function that can be called on a schema after its generation?

**Comment by yulric** [comment]
I'm not sure how this new argument prevents that? Can you give an example?

Your solution is definitely much more flexible and I can go either way. We can discuss with @DougManuel.

**Comment by yulric** [comment]
For sure, the most flexible option is the function approach. From a user's perspective, I *think* the argument approach is better because they can just create a JSON/YAML file with addition and use it in the function.
