### ISSUE TITLE
implement rules for min/max value

### ISSUE THREAD

**Issue by yulric** [Big-Life-Lab/PHES-ODM-Validation#37]
Add a new validation rule to support minimum and maximum values

Specs
* https://big-life-lab.github.io/PHES-ODM-Validation/validation-rules/less_than_min_value.html
* https://big-life-lab.github.io/PHES-ODM-Validation/validation-rules/greater_than_max_value.html

**Comment by zargot** [comment]
From reading this spec, and reading the cerberus spec, it seems like Cerberus's `min`/`max` already is what we want. "The ODM dictionary is currently written so that the defined minimum values are inclusive." `min` is also inclusive, meaning that `min=10` would include 10. Am I missing something?

**Comment by yulric** [comment]
It looks like cerberus uses gt and lt and not something like gte and lte, https://docs.python-cerberus.org/en/stable/validation-rules.html#min-max? Unless I'm missing something.

**Comment by zargot** [comment]
Yeah, but I'm guessing they are used the other way around, for example: `if x < min: return error`, where `<` is `__lt__`. I can test it to confirm.

**Comment by yulric** [comment]
Yup, why don't you test it and let me know

**Comment by yulric** [comment]
Blocked by #65

**Comment by zargot** [comment]
I've confirmed that Cerberus uses inclusive min/max. It can easily be tested with the following piece of code:
```
from cerberus import Validator
v = Validator()
schema = {'age': {'type': 'integer', 'min': 1, 'max': 2}}
assert v.validate({'age': 1}, schema) is True
assert v.validate({'age': 2}, schema) is True
```
